export const LOGIN_PATH = 'LOGIN';

export const DASHBOARD = 'DASHBOARD';
export const REGISTER = 'REGISTER';
export const APPLICANT = {DASHBOARD: 'APPLICANT_DASHBOARD'};
export const RECRUITER = {DASHBOARD: 'RECRUITER_DASHBOARD'};
export const ADMINISTRATOR = {DASHBOARD: 'ADMINISTRATOR_DASHBOARD'};
